### ISSUE TITLE
setup_template.py script to automate setting up the template

### ISSUE THREAD

**Issue by nx10** [cmi-dair/template-python-repository#26]
- **What is the current behavior?**

The user has to manually rename a couple files and strings to their repo and module names.

- **What is the motivation / use case for changing the behavior?**

Lazyness

- **If relevant, please tell us about your computing environment:**

![](https://media.tenor.com/Wslm3Bd6ZRAAAAAC/bill-gates-jump.gif)

- **Other information**

1. Ask user for repo name (default=`git remote get-url origin`)
2. Ask user for module name (default=repo name)
3. Change all strings and file names
4. Delete self

**Comment by ReinderVosDeWael** [comment]
Why doe this GIF even exist
