### ISSUE TITLE
Make setup script smarter

### ISSUE THREAD

**Issue by nx10** [cmi-dair/template-python-repository#35]
The setup script should

- ~Ask what license the user wants and download and update accordingly (Related: https://github.com/cmi-dair/template-python-repository/issues/29 )~
- Setup pre-commit
  - If pre-commit is accessible (available from the python env the user is running the setup script in; this should not be a requirement to run the setup):
    - Update the pre-commit versions in .pre-commit-config.yaml and install the pre-commit hooks..
    - Check the pre-commit setup box in the Readme checklist
  - If  pre-commit is **not** accessible
    - Do nothing (in this step)

**Comment by ReinderVosDeWael** [comment]
As part of setting up the pre-commit, we should probably refactor the setup script to be more modularized. #36 already shows that a license selection adds quite a bit of code complexity, and this will only get more complex the more features we want to add to this script.

**Comment by nx10** [comment]
The last parts of this issue are now resolved by the now activated bot that keeps the pre-cpommit hooks up to date (thanks @ReinderVosDeWael ). This will only happen in this repo not in child repos.
