### ISSUE TITLE
Tests workflow returns error (fails) when no tests are present

### ISSUE THREAD

**Issue by nx10** [cmi-dair/template-python-repository#69]
No tests should just report coverage 0% - not a red cross

**Comment by ReinderVosDeWael** [comment]
Do you have an example action where this occurs? Where does it error?

**Comment by nx10** [comment]
I looked a little bit into it and pytest responds error code 5 if this happens - if there is an easy way to ignore this great, otherwise a dummy test 

```Python
def test_dummy():
    pass
```

can be used as a workaround and we can close this.

**Comment by ReinderVosDeWael** [comment]
Let me run a few quick tests to see how hard this would be to address. Though, I'm honestly a little tempted to say that this is a feature not a bug i.e. a test workflow _should_ fail if no tests are found. In that case I'd expect the user to delete the test workflow, or fix the issue that's causing tests to not be found.

**Comment by ReinderVosDeWael** [comment]
Right - so I don't think there's any way to work around it other than as you suggested creating a dummy test, or explicitly capturing exit code 5 and ignoring it, either in the action or in a `conftest.py`. 

To me, putting either solution in the template seems like it adds complexity without being very helpful and I'd suggest considering this failure a "feature".
